Sprint1
ClevertecFrontendLab/sprint1-smokimod pull request #1
Opened 2023-01-29 15:44 UTC by smokimod

2023-01-29 15:47 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675007264/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675007264/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675007264/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675007264/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675007264/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675007264/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675007264/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675007264/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675007264/content-window.png)

2023-01-29 16:11 UTC, klichkovskiy requested changes

2023-01-29 16:11 UTC, klichkovskiy commented on src/components/book/book-page.jsx
> +                {/* <div className='list-item'>Бизнес книги</div>
удали закомментированный код

2023-01-29 16:11 UTC, klichkovskiy commented on src/components/book/book-page.jsx
> +    <div className="book-container">
![image](https://user-images.githubusercontent.com/62481116/215338878-a9493af9-604a-4d1b-85d5-674c7679d72d.png)
Отступ не по макету

2023-01-29 16:11 UTC, klichkovskiy commented on src/index.js
> +        <Routes>
![image](https://user-images.githubusercontent.com/62481116/215339230-4ce8468e-d53c-4845-a8db-3f6f4a75a328.png)
А это что такое?
![image](https://user-images.githubusercontent.com/62481116/215339262-29dd6d43-a148-40fb-b04c-bc15618d1d90.png)
Исправь по всему приложению!

2023-01-31 17:29 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675186151/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675186151/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675186151/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675186151/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675186151/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675186151/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675186151/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675186151/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675186151/content-window.png)

2023-01-31 19:12 UTC, klichkovskiy requested changes

2023-01-31 19:12 UTC, klichkovskiy commented on src/components/layout/layout-main-page/main/main-page.jsx
> +                            <svg role='img' className='btn-squre' width="18" height="19" viewBox="0 0 18 19" xmlns="http://www.w3.org/2000/svg" aria-labelledby="button-label"
импортируй свг как картинку. исправь по всему коду

2023-01-31 19:12 UTC, klichkovskiy commented on src/components/layout/layout-main-page/main/main-page.jsx
> +export const MainPage = () => {
![image](https://user-images.githubusercontent.com/62481116/215857639-c6d3786c-dab2-4955-8e0c-57b1bdd6d440.png)
Исправь

2023-01-31 19:12 UTC, klichkovskiy commented on src/components/layout/layout-main-page/main/main-page.jsx
> +export const MainPage = () => {
Исправь
![image](https://user-images.githubusercontent.com/62481116/215857740-bd2a62ca-b0b2-40f1-bcf2-4d33370325e5.png)

2023-01-31 19:12 UTC, klichkovskiy commented on src/components/layout/layout-main-page/main-books/books-squre/books-squre.jsx
> +                    <Link to='/books/all/bookId' key={Math.random()} id='card' >
Это нужно было в компонент вынести
![image](https://user-images.githubusercontent.com/62481116/215858064-a0d24a25-c800-476b-9625-1097d085a178.png)
Исправь

2023-01-31 19:12 UTC, klichkovskiy commented on src/components/book/book-page.jsx
> +                    <AdditionalInfoBook />
![image](https://user-images.githubusercontent.com/62481116/215858343-126e6c10-42dd-499c-8d85-d38864c70e5b.png)
Исправь

2023-01-31 19:12 UTC, klichkovskiy commented on src/components/book/book-page.jsx
> +            <div className='list-container'>
![image](https://user-images.githubusercontent.com/62481116/215858544-27b6b759-3325-428c-881b-45b5a15e4e46.png)
Исправь

2023-01-31 19:12 UTC, klichkovskiy commented on src/components/book/book-page.jsx
> +                    <AdditionalInfoBook />
![image](https://user-images.githubusercontent.com/62481116/215859377-e218e129-2ec1-4274-94a2-445fecd8435c.png)
Исправь

2023-01-31 19:12 UTC, klichkovskiy commented on src/components/book/book-page.jsx
> +                    <BookComents />
![image](https://user-images.githubusercontent.com/62481116/215859477-31d718f2-a44d-446c-8726-e3abe756b447.png)
сделай переход раньше

2023-02-01 08:26 UTC, smokimod commented on src/components/layout/layout-main-page/main-books/books-squre/books-squre.jsx
> +                    <Link to='/books/all/bookId' key={Math.random()} id='card' >
Не совсем понимаю, что именно в компонент обернуть. Ведь книжка в виде плитки и так уже компонент

2023-02-01 08:31 UTC, smokimod commented on src/components/layout/layout-main-page/main/main-page.jsx
> +export const MainPage = () => {
Сойдет если шрифт до определенного момента ширины экрана уменьшается, а потом и вовсе исчезает оставляя инпут без плейсхолдера?

2023-02-01 16:13 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675268010/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675268010/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675268010/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675268010/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675268010/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675268010/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675268010/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675268010/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/smokimod/1675268010/content-window.png)

2023-02-01 16:26 UTC, merged